# Generated by Django 3.2.4 on 2021-07-10 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CardInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardno', models.IntegerField(max_length=10)),
                ('taskn', models.CharField(max_length=50)),
                ('taskid', models.CharField(max_length=20)),
                ('team', models.CharField(max_length=20)),
                ('department', models.CharField(max_length=20)),
                ('expecttime', models.CharField(max_length=20)),
                ('addinfo', models.TextField()),
                ('duedate', models.DateField()),
            ],
            options={
                'db_table': 'CardInfo',
            },
        ),
    ]
